name: codelab3
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Mengubah versi SDK untuk mendukung null safety

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  # Tambahkan ini
  firebase_auth: ^4.16.0
  shared_preferences: ^2.2.0
  firebase_core: ^2.32.0    # Latest compatible version
  cloud_firestore: ^4.17.5
  intl: ^0.19.0
  provider: ^6.1.1
  google_fonts: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true