// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADhoWTPKr1LTT7IKf6VTj9LIQKcbkYs3I',
    appId: '1:781080944932:web:78d686ac044651225b13b1',
    messagingSenderId: '781080944932',
    projectId: 'codelab3-ce5b9',
    authDomain: 'codelab3-ce5b9.firebaseapp.com',
    storageBucket: 'codelab3-ce5b9.appspot.com',
    measurementId: 'G-W5PMJRXF8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoAB0_EMg3QLQMZ6wmB7lKg7HdwPa_koo',
    appId: '1:781080944932:android:b2de12a92e78c1895b13b1',
    messagingSenderId: '781080944932',
    projectId: 'codelab3-ce5b9',
    storageBucket: 'codelab3-ce5b9.appspot.com',
  );
}
